# Docker Compose file version
version: '3.8'

# Define the services (containers) to run
services:
  # Name of our service
  dev-environment:
    # Tell Docker Compose to build the image from the Dockerfile in the current directory
    build: .
    # Name the container for easier identification
    container_name: multi_lang_dev
    # This is the bind mount!
    # It maps the current directory on your host machine ('.')
    # to the '/app' directory inside the container.
    volumes:
      - .:/app
    # Keep the terminal active so the container doesn't stop
    tty: true
